### ISSUE TITLE
Add a fft visualization

### ISSUE THREAD

**Issue by FoxyHawk** [intrlocutr/nightcoreify#1]
Use the audio track to output a video graph of the fft ~~(there is quite a lot of nodejs packages to output to a web page in real time, did not find any which output to a video)~~.

EDIT: found http://lukaprincic.si/development-log/ffmpeg-audio-visualization-tricks

Combine the main video and the visualization into one (ffmpeg is the way to go).

Enjoy

**Comment by intrlocutr** [comment]
Nice idea--I've modified the ffmpeg call to overlay a histogram over the image.
