### ISSUE TITLE
NOT AN ISSUE [Question]

### ISSUE THREAD

**Issue by Glatrix** [intrlocutr/nightcoreify#3]
Any way to convert this to soundcloud? Make it pull its music from souncloud and post it there?

**Comment by intrlocutr** [comment]
It is certainly possible, and [soundcloud does have an api](https://developers.soundcloud.com/docs)--interestingly their api can expose direct stream urls for tracks. (Even if they didn't, with enough patience, a scraper could be written) I assume the stream could be piped directly into ffmpeg which would make it easier from a logistics standpoint, to download the actual tracks. However at the moment I have no plans to add any additional functions to this script, as I'd like to keep it as simple as possible for efficiency (it runs pretty slowly on AWS), but you are more than welcome to fork it and implement the soundcloud functionality. You could even add a cli switch for running it from the terminal, like `-y` for youtube and `-s` for soundcloud.
