### ISSUE TITLE
non type !!

### ISSUE THREAD

**Issue by axen1** [intrlocutr/nightcoreify#6]

**Comment by axen1** [comment]
![image](https://user-images.githubusercontent.com/31828262/194755119-26ecca10-cfc6-4dc5-a8a8-bec14d0a299a.png)

**Comment by intrlocutr** [comment]
The script is looking for a YouTube API v3 token (in JSON format) in the environment variable `YT_TOKEN`. [These fields](https://github.com/googleapis/google-auth-library-python/blob/80639b4548c7451bdd69772e69b03c0b33481e3d/google/oauth2/credentials.py#L84), except the `Optional` ones, should be present in the JSON.

If you do not have YouTube API credentials, note that newly created credentials are no longer allowed to upload.
