### ISSUE TITLE
Hey Bro 

### ISSUE THREAD

**Issue by axen1** [intrlocutr/nightcoreify#7]
I'm new to software, please explain to me with simple logic or a gif with a picture.

![image](https://user-images.githubusercontent.com/31828262/194774465-36291f53-b67f-4062-84e6-eb5d56969574.png)

**Comment by intrlocutr** [comment]
I can't provide support for general software development principles as part of this project. I've listed a YouTube API key as a requirement for this script. It is expected that you have one prior to even opening an issue. If you don't know what that is, this project isn't for you; but you can [check out the YouTube channel I've created with this project already deployed](https://www.youtube.com/channel/UChMRsMd8YxgwztGrQMG44CQ). Do not open any more extraneous issues.
